### ISSUE TITLE
Project not buildable / Website Rewrite?

### ISSUE THREAD

**Issue by CMDR-WDX** [SpyTec/EDAssets#180]
**Is your feature request related to a problem? Please describe.**
Website cannot be built using the instructions described in the README.

Trying to `npm i` has the following errors:

```
➜  EDAssets git:(master) npm i     
npm warn old lockfile
npm warn old lockfile The package-lock.json file was created with an old version of npm,
npm warn old lockfile so supplemental metadata must be fetched from the registry.
npm warn old lockfile
npm warn old lockfile This is a one-time fix-up, please be patient...
npm warn old lockfile
npm warn old lockfile Could not fetch metadata for vue-loader-v16@16.0.0 vue-loader-v16: No matching version found for vue-loader-v16@16.0.0.
npm warn old lockfile     at module.exports (/home/waldi/.nvm/versions/node/v20.18.0/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:215:23)
npm warn old lockfile     at RegistryFetcher.manifest (/home/waldi/.nvm/versions/node/v20.18.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:130:54)
npm warn old lockfile     at async /home/waldi/.nvm/versions/node/v20.18.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:712:24 {
npm warn old lockfile   code: 'ETARGET',
npm warn old lockfile   type: 'version',
npm warn old lockfile   wanted: '16.0.0',
npm warn old lockfile   versions: [
npm warn old lockfile     '16.0.0-beta.5',
npm warn old lockfile     '16.0.0-beta.5.1',
npm warn old lockfile     '16.0.0-beta.5.2',
npm warn old lockfile     '16.0.0-beta.5.3',
npm warn old lockfile     '16.0.0-beta.5.4'
npm warn old lockfile   ],
npm warn old lockfile   distTags: { latest: '16.0.0-beta.5.4' },
npm warn old lockfile   defaultTag: 'latest'
npm warn old lockfile }
npm warn deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated webpack-chain@6.5.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated vue-analytics@5.22.1: Sorry but vue-analytics is no longer maintained. I would suggest you switch to vue-gtag, with love, the guy who made the package.
npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm warn deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm warn deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm warn deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm warn deprecated vue@2.6.12: Vue 2 has reached EOL and is no longer actively maintained. See https://v2.vuejs.org/eol/ for more details.
npm warn deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm warn deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm warn deprecated q@1.5.1: You or someone you depend on is using Q, the JavaScript Promise library that gave JavaScript developers strong feelings about promises. They can almost certainly migrate to the native JavaScript promise now. Thank you literally everyone for joining me in this bet against the odds. Be excellent to each other.
npm warn deprecated
npm warn deprecated (For a CapTP with native promises, see @endo/eventual-send and @endo/captp)
npm warn deprecated osenv@0.1.5: This package is no longer supported.
npm warn deprecated npmlog@4.1.2: This package is no longer supported.
npm warn deprecated move-concurrently@1.0.1: This package is no longer supported.
npm warn deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm warn deprecated node-sass@4.14.1: Node Sass is no longer supported. Please use `sass` or `sass-embedded` instead.
npm warn deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
npm warn deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
npm warn deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm warn deprecated fs-write-stream-atomic@1.0.10: This package is no longer supported.
npm warn deprecated gauge@2.7.4: This package is no longer supported.
npm warn deprecated fstream@1.0.12: This package is no longer supported.
npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm warn deprecated figgy-pudding@3.5.2: This module is no longer supported.
npm warn deprecated highlight.js@10.4.0: Potential vulnerability. Please upgrade to @latest
npm warn deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm warn deprecated copy-concurrently@1.0.5: This package is no longer supported.
npm warn deprecated consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm warn deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm warn deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm warn deprecated are-we-there-yet@1.1.5: This package is no longer supported.
npm warn deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm warn deprecated eslint@5.16.0: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm warn deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm warn deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm warn deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm warn deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm warn deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm warn deprecated @babel/plugin-proposal-optional-catch-binding@7.12.1: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm warn deprecated @babel/plugin-proposal-unicode-property-regex@7.12.1: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.12.1: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm warn deprecated @babel/plugin-proposal-class-properties@7.12.1: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated @babel/plugin-proposal-async-generator-functions@7.12.1: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm warn deprecated @babel/plugin-proposal-json-strings@7.12.1: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-json-strings instead.
npm warn deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm warn deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm warn deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm warn deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm warn deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm warn deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm warn deprecated eslint@4.19.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm error code 1
npm error path /media/projects/2024-Q4/EDAssets/node_modules/node-sass
npm error command failed
npm error command sh -c node scripts/build.js
npm error Building: /home/waldi/.nvm/versions/node/v20.18.0/bin/node /media/projects/2024-Q4/EDAssets/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm error gyp info it worked if it ends with ok
npm error gyp verb cli [
npm error gyp verb cli   '/home/waldi/.nvm/versions/node/v20.18.0/bin/node',
npm error gyp verb cli   '/media/projects/2024-Q4/EDAssets/node_modules/node-gyp/bin/node-gyp.js',
npm error gyp verb cli   'rebuild',
npm error gyp verb cli   '--verbose',
npm error gyp verb cli   '--libsass_ext=',
npm error gyp verb cli   '--libsass_cflags=',
npm error gyp verb cli   '--libsass_ldflags=',
npm error gyp verb cli   '--libsass_library='
npm error gyp verb cli ]
npm error gyp info using node-gyp@3.8.0
npm error gyp info using node@20.18.0 | linux | x64
npm error gyp verb command rebuild []
npm error gyp verb command clean []
npm error gyp verb clean removing "build" directory
npm error gyp verb command configure []
npm error gyp verb check python checking for Python executable "python2" in the PATH
npm error gyp verb `which` failed Error: not found: python2
npm error gyp verb `which` failed     at getNotFoundError (/media/projects/2024-Q4/EDAssets/node_modules/which/which.js:13:12)
npm error gyp verb `which` failed     at F (/media/projects/2024-Q4/EDAssets/node_modules/which/which.js:68:19)
npm error gyp verb `which` failed     at E (/media/projects/2024-Q4/EDAssets/node_modules/which/which.js:80:29)
npm error gyp verb `which` failed     at /media/projects/2024-Q4/EDAssets/node_modules/which/which.js:89:16
npm error gyp verb `which` failed     at /media/projects/2024-Q4/EDAssets/node_modules/isexe/index.js:42:5
npm error gyp verb `which` failed     at /media/projects/2024-Q4/EDAssets/node_modules/isexe/mode.js:8:5
npm error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:197:21)
npm error gyp verb `which` failed  python2 Error: not found: python2
npm error gyp verb `which` failed     at getNotFoundError (/media/projects/2024-Q4/EDAssets/node_modules/which/which.js:13:12)
npm error gyp verb `which` failed     at F (/media/projects/2024-Q4/EDAssets/node_modules/which/which.js:68:19)
npm error gyp verb `which` failed     at E (/media/projects/2024-Q4/EDAssets/node_modules/which/which.js:80:29)
npm error gyp verb `which` failed     at /media/projects/2024-Q4/EDAssets/node_modules/which/which.js:89:16
npm error gyp verb `which` failed     at /media/projects/2024-Q4/EDAssets/node_modules/isexe/index.js:42:5
npm error gyp verb `which` failed     at /media/projects/2024-Q4/EDAssets/node_modules/isexe/mode.js:8:5
npm error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:197:21) {
npm error gyp verb `which` failed   code: 'ENOENT'
npm error gyp verb `which` failed }
npm error gyp verb check python checking for Python executable "python" in the PATH
npm error gyp verb `which` succeeded python /usr/bin/python
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm error gyp ERR! stack   File "<string>", line 1
npm error gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm error gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm error gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm error gyp ERR! stack 
npm error gyp ERR! stack     at genericNodeError (node:internal/errors:984:15)
npm error gyp ERR! stack     at wrappedFn (node:internal/errors:538:14)
npm error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:422:12)
npm error gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm error gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:457:11)
npm error gyp ERR! stack     at Socket.emit (node:events:519:28)
npm error gyp ERR! stack     at Pipe.<anonymous> (node:net:339:12)
npm error gyp ERR! System Linux 6.11.9-arch1-1
npm error gyp ERR! command "/home/waldi/.nvm/versions/node/v20.18.0/bin/node" "/media/projects/2024-Q4/EDAssets/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm error gyp ERR! cwd /media/projects/2024-Q4/EDAssets/node_modules/node-sass
npm error gyp ERR! node -v v20.18.0
npm error gyp ERR! node-gyp -v v3.8.0
npm error gyp ERR! not ok 
npm error Build failed with error code: 1
npm error A complete log of this run can be found in: /home/waldi/.npm/_logs/2024-11-23T18_48_20_954Z-debug-0.log
➜  EDAssets git:(master) node --version
v20.18.0
➜  EDAssets git:(master) npm --version
10.8.2
➜  EDAssets git:(master) 
```

**Describe the solution you'd like**
The website's dependencies are marked outdated and are no longer supported. I would suggest a rewrite from scratch using either a newer Version of Vue / Vite or something like Astro. 

If you are generally willing to accept "full rewrite" PRs, I could try my luck with it :)

**Describe alternatives you've considered**
Could try to upgrade the dependencies, but honestly, that seems like more pain than it is worth

**Additional context**
Build attempted on Node v20.18.0 with npm v.10.8.2 on archlinux 6.11.9-arch1-1

**Comment by Venefilyn** [comment]
Think I might have mentioned it in the Discord. But yeah full rewrite is fine, have fun. I'll review and give feedback if wanted.

Would be great if we can get rid of the zip files or have them autogenerated by CI pipeline. Same with making it easier to upload assets in some capacity to reduce developer burden - adding assets has been a pain in the long run for me IMO, which is partly why so many PRs and issues are open still for new assets
